export const countries = [
  { value: "br", label: "Brazil", flag: "🇧🇷" },
  { value: "us", label: "United States", flag: "🇺🇸" },
  { value: "pt", label: "Portugal", flag: "🇵🇹" },
  { value: "de", label: "Germany", flag: "🇩🇪" },
  { value: "fr", label: "France", flag: "🇫🇷" },
  { value: "it", label: "Italy", flag: "🇮🇹" },
  { value: "es", label: "Spain", flag: "🇪🇸" },
  { value: "nl", label: "Netherlands", flag: "🇳🇱" },
  { value: "be", label: "Belgium", flag: "🇧🇪" },
  { value: "ch", label: "Switzerland", flag: "🇨🇭" },
  { value: "at", label: "Austria", flag: "🇦🇹" },
  { value: "se", label: "Sweden", flag: "🇸🇪" },
  { value: "no", label: "Norway", flag: "🇳🇴" },
  { value: "dk", label: "Denmark", flag: "🇩🇰" },
  { value: "fi", label: "Finland", flag: "🇫🇮" },
  { value: "is", label: "Iceland", flag: "🇮🇸" },
  { value: "ie", label: "Ireland", flag: "🇮🇪" },
  { value: "mt", label: "Malta", flag: "🇲🇹" },
  { value: "cy", label: "Cyprus", flag: "🇨🇾" },
  { value: "lv", label: "Latvia", flag: "🇱🇻" },
  { value: "lt", label: "Lithuania", flag: "🇱🇹" },
  { value: "hu", label: "Hungary", flag: "🇭🇺" },
  { value: "pl", label: "Poland", flag: "🇵🇱" },
  { value: "ro", label: "Romania", flag: "🇷🇴" },
  { value: "bg", label: "Bulgaria", flag: "🇧🇬" },
  { value: "gr", label: "Greece", flag: "🇬🇷" },
  { value: "cz", label: "Czech Republic", flag: "🇨🇿" },
  { value: "sk", label: "Slovakia", flag: "🇸🇰" },
  { value: "hr", label: "Croatia", flag: "🇭🇷" },
  { value: "ba", label: "Bosnia and Herzegovina", flag: "🇧🇦" },
]